# Generated by Django 2.1.4 on 2019-01-08 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Clusters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('serial_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('course_top_code', models.PositiveSmallIntegerField()),
                ('units', models.PositiveSmallIntegerField()),
                ('advisory', models.CharField(max_length=1000, null=True)),
                ('hours', models.TimeField()),
                ('transferable', models.BooleanField()),
                ('course_instruction_type', models.CharField(max_length=256, null=True)),
                ('credit_status', models.CharField(max_length=256, null=True)),
                ('gen_id', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'Course Type',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256, null=True)),
                ('url', models.URLField()),
                ('attachment', models.FileField(blank=True, upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_path.Courses')),
            ],
            options={
                'db_table': 'Milestone',
            },
        ),
        migrations.CreateModel(
            name='MilestoneResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FilePathField(blank=True)),
                ('video', models.FilePathField(blank=True)),
                ('gif_animation', models.FilePathField(blank=True)),
            ],
            options={
                'db_table': 'Milestone Resource',
            },
        ),
        migrations.CreateModel(
            name='MilestoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Milestone Type',
            },
        ),
        migrations.CreateModel(
            name='OverviewContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topcode', models.CharField(max_length=256, null=True)),
                ('learning_outcomes', models.CharField(max_length=256, null=True)),
                ('skills_learned', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Overview Content',
            },
        ),
        migrations.CreateModel(
            name='PathClusterProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('no_of_courses', models.IntegerField()),
                ('min_gpa', models.SmallIntegerField()),
                ('duration', models.IntegerField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_path.Clusters')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_path.Courses')),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_path.OverviewContent')),
            ],
            options={
                'db_table': 'Cluster Program',
            },
        ),
        migrations.CreateModel(
            name='PathTypeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Path Name',
                'ordering': ['path_name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_path.Clusters')),
            ],
            options={
                'db_table': 'Program',
                'ordering': ['name', 'cluster'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(null=True)),
                ('in_years_or_month', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'Program Duration',
            },
        ),
        migrations.CreateModel(
            name='ProgramSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=256, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_path.Program')),
            ],
            options={
                'db_table': 'Program Skills',
            },
        ),
        migrations.AddField(
            model_name='pathclusterprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_path.Program'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_path.MilestoneResource'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_path.MilestoneType'),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_path.Milestone'),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_path.CourseType'),
        ),
    ]
